apiVersion: apps/v1
kind: Deployment
metadata:
   name: user
   labels:
      app: nodejs
      project: roboshop
      service: user
      env: dev
spec:
   replicas: 1
   selector:
      matchLabels:
         app: nodejs
         project: roboshop
         service: user
         env: dev
   template:
      metadata:
         labels:
            app: nodejs
            project: roboshop
            service: user
            env: dev
      spec:
         serviceAccountName: user
         containers:
            - name: user
              image: hemanthtadikonda/user:1.1.0
              ports:
                 - containerPort: 8080
              envFrom:
                 -  configMapRef:
                       name: user-config
              resources:
                 requests:
                    memory: "500Mi"
                    cpu: "250m"
                 limits:
                    memory: "500Mi"
                    cpu: "250m"
              livenessProbe:
                 httpGet:
                    path: /health
                    port: 8080
                 initialDelaySeconds: 10
                 periodSeconds: 5
              readinessProbe:
                 httpGet:
                    path: /health
                    port: 8080
                 initialDelaySeconds: 10
                 periodSeconds: 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
   name: user
---
apiVersion: v1
kind: Service
metadata:
   name: user
spec:
   selector:
      app: nodejs
      project: roboshop
      service: user
      env: dev
   ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: user-config
data:
   MONGO_URL: "mongodb://mongodb:27017/users"
   REDIS_HOST: 'redis'